sudo: false

language: python

addons:
    apt:
        packages:
            - libeigen3-dev
            - libboost-all-dev

language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"

env:
    - NUMPY_VERSION=1.8
    - NUMPY_VERSION=1.9
    - NUMPY_VERSION=1.10

before_install:
    - wget http://ceres-solver.org/ceres-solver-1.10.0.tar.gz
    - tar -xf ceres-solver-1.10.0.tar.gz
    - mv ceres-solver-1.10.0 ceres
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda2/bin:$PATH
    - conda update --yes conda

install:
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test
    - conda install --yes numpy=$NUMPY_VERSION nose Cython

    - CXX=g++ python setup.py build_ext --inplace

script:
    - nosetests -v
